services:
  _defaults:
    autowire: true
#    autoconfigure: true
  eduMedia\TagBundle\Service\TagService:
    public: true
  eduMedia\TagBundle\Command\TagCreateCommand:
    tags: [ console.command ]