services:
  _defaults:
    autowire: true
  eduMedia\TagBundle\Service\TagService:
    public: true
  eduMedia\TagBundle\EventListener\TagListener:
    tags: [ { name: 'doctrine.event_listener', event: 'preRemove' } ]
  eduMedia\TagBundle\Form\TagType:
    tags: [ form.type ]